# Generated by Django 5.0.1 on 2024-01-18 15:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="missa",
            old_name="escala_id",
            new_name="escala",
        ),
        migrations.RenameField(
            model_name="participacao",
            old_name="ministro_id",
            new_name="ministro",
        ),
        migrations.AddField(
            model_name="missa",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="missa",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="participacao",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="participacao",
            name="missa",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.missa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participacao",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="escala",
            table="tb_escala",
        ),
        migrations.AlterModelTable(
            name="missa",
            table="tb_missa",
        ),
        migrations.AlterModelTable(
            name="participacao",
            table="tb_participacao",
        ),
    ]
