# Generated by Django 5.0.1 on 2024-01-09 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="escala",
            table="tb_escala",
        ),
        migrations.AlterModelTable(
            name="missa",
            table="tb_missa",
        ),
        migrations.AlterModelTable(
            name="participacao",
            table="tb_participacao",
        ),
    ]
