# Generated by Django 5.0.1 on 2024-01-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_escala_id_missa_escala_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participacao",
            name="missa",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.missa",
            ),
        ),
    ]
